### ISSUE TITLE
可以指导一下window下编译吗？

### ISSUE THREAD

**Issue by LL223851** [tuyuai/TuYuIDCard#3]
我在windows下还是没有编译成功，最大的问题是decode.cpp编码问题，始终通过不了，vs2019+windows sdk 10环境，已经生成项目文件了

**Comment by tuyuai** [comment]
已更新

**Comment by LL223851** [comment]
谢谢，非常感谢，正在准备评估

**Comment by LL223851** [comment]
一次编译成功，这次弄得非常好啦
